# Generated by Django 5.1 on 2024-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0002_rename_reaction_postreaction_remove_fileupload_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profanity_filter',
            field=models.BooleanField(default=True),
        ),
    ]
