# Generated by Django 5.1 on 2024-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0003_rename_author_post_user_userprofile_profanity_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
