# Generated by Django 5.1 on 2024-09-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
