# Generated by Django 5.1 on 2024-09-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0006_group_is_protected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
