# Generated by Django 5.1 on 2024-09-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0007_remove_post_parent_remove_post_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamUpapp.post'),
        ),
    ]
