# Generated by Django 5.1 on 2024-09-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0008_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discordLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='find',
            field=models.BooleanField(default=False),
        ),
    ]
