# Generated by Django 5.1 on 2024-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0009_userprofile_description_userprofile_discordlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discordLink',
            field=models.URLField(blank=True),
        ),
    ]
