# Generated by Django 5.1 on 2024-09-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0010_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='discordLink',
            new_name='discord',
        ),
    ]
