# Generated by Django 5.1 on 2024-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0012_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ranks',
            field=models.JSONField(default=dict),
        ),
    ]
