# Generated by Django 5.1 on 2024-09-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamUpapp', '0013_userprofile_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discord',
            field=models.TextField(blank=True, null=True),
        ),
    ]
